### PR TITLE
fix(language-server): use https and http proxy agent to make fetcher …

### LINKED ISSUE #285: Auto complete doesn't work with corporate proxy
Hi,

Excellent to see SAP taking ownership of these extensions. However the extension doesn't work through corporate proxy, even though it has been added in VS code settings and windows environment variables.

See output below

c:\Users\KjaerJ\AppData\Roaming\Code\User\globalStorage\saposs.vscode-ui5-language-assistant\ui5-resources-cache\1.71.14 will be used to cache UI5 resources
[Error - 9:46:22 am] Request textDocument/hover failed.
Message: Request textDocument/hover failed with message: request to https://sapui5.hana.ondemand.com/1.71.14/test-resources/sap/ca/scfld/md/designtime/api.json failed, reason: connect ETIMEDOUT 23.48.30.95:443
Code: -32603
(node:13616) UnhandledPromiseRejectionWarning: FetchError: request to https://sapui5.hana.ondemand.com/1.71.14/test-resources/sap/ca/scfld/md/designtime/api.json failed, reason: connect ETIMEDOUT 23.48.30.95:443
at ClientRequest. (c:\Users\KjaerJ.vscode\extensions\saposs.vscode-ui5-language-assistant-1.5.1\node_modules@ui5-language-assistant\language-server\dist\server.js:48289:11)
at ClientRequest.emit (events.js:203:13)
at TLSSocket.socketErrorListener (_http_client.js:399:9)
at TLSSocket.emit (events.js:203:13)
at emitErrorNT (internal/streams/destroy.js:91:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:13616) UnhandledPromiseRejectionWarning: FetchError: request to https://sapui5.hana.ondemand.com/1.71.14/test-resources/sap/ca/scfld/md/designtime/api.json failed, reason: connect ETIMEDOUT 23.48.30.95:443
at ClientRequest. (c:\Users\KjaerJ.vscode\extensions\saposs.vscode-ui5-language-assistant-1.5.1\node_modules@ui5-language-assistant\language-server\dist\server.js:48289:11)
at ClientRequest.emit (events.js:203:13)
at TLSSocket.socketErrorListener (_http_client.js:399:9)
at TLSSocket.emit (events.js:203:13)
at emitErrorNT (internal/streams/destroy.js:91:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:13616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:13616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:13616) UnhandledPromiseRejectionWarning: FetchError: request to https://sapui5.hana.ondemand.com/1.71.14/test-resources/sap/ca/scfld/md/designtime/api.json failed, reason: connect ETIMEDOUT 23.48.30.95:443
at ClientRequest. (c:\Users\KjaerJ.vscode\extensions\saposs.vscode-ui5-language-assistant-1.5.1\node_modules@ui5-language-assistant\language-server\dist\server.js:48289:11)
at ClientRequest.emit (events.js:203:13)
at TLSSocket.socketErrorListener (_http_client.js:399:9)
at TLSSocket.emit (events.js:203:13)
at emitErrorNT (internal/streams/destroy.js:91:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:13616) UnhandledPromiseRejectionWarning: FetchError: request to https://sapui5.hana.ondemand.com/1.71.14/test-resources/sap/ca/scfld/md/designtime/api.json failed, reason: connect ETIMEDOUT 23.48.30.95:443
at ClientRequest. (c:\Users\KjaerJ.vscode\extensions\saposs.vscode-ui5-language-assistant-1.5.1\node_modules@ui5-language-assistant\language-server\dist\server.js:48289:11)
at ClientRequest.emit (events.js:203:13)
at TLSSocket.socketErrorListener (_http_client.js:399:9)
at TLSSocket.emit (events.js:203:13)
at emitErrorNT (internal/streams/destroy.js:91:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:13616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[Error - 9:46:31 am] Request textDocument/hover failed.
Message: Request textDocument/hover failed with message: request to https://sapui5.hana.ondemand.com/1.71.14/test-resources/sap/ca/scfld/md/designtime/api.json failed, reason: connect ETIMEDOUT 23.48.30.95:443
Code: -32603
[Error - 9:46:32 am] Request textDocument/completion failed.
Message: Request textDocument/completion failed with message: request to https://sapui5.hana.ondemand.com/1.71.14/test-resources/sap/ca/scfld/md/designtime/api.json failed, reason: connect ETIMEDOUT 23.48.30.95:443
Code: -32603
(node:13616) UnhandledPromiseRejectionWarning: FetchError: request to https://sapui5.hana.ondemand.com/1.71.14/test-resources/sap/ca/scfld/md/designtime/api.json failed, reason: connect ETIMEDOUT 23.48.30.95:443
at ClientRequest. (c:\Users\KjaerJ.vscode\extensions\saposs.vscode-ui5-language-assistant-1.5.1\node_modules@ui5-language-assistant\language-server\dist\server.js:48289:11)
at ClientRequest.emit (events.js:203:13)
at TLSSocket.socketErrorListener (_http_client.js:399:9)
at TLSSocket.emit (events.js:203:13)
at emitErrorNT (internal/streams/destroy.js:91:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:13616) UnhandledPromiseRejectionWarning: FetchError: request to https://sapui5.hana.ondemand.com/1.71.14/test-resources/sap/ca/scfld/md/designtime/api.json failed, reason: connect ETIMEDOUT 23.48.30.95:443
at ClientRequest. (c:\Users\KjaerJ.vscode\extensions\saposs.vscode-ui5-language-assistant-1.5.1\node_modules@ui5-language-assistant\language-server\dist\server.js:48289:11)
at ClientRequest.emit (events.js:203:13)
at TLSSocket.socketErrorListener (_http_client.js:399:9)
at TLSSocket.emit (events.js:203:13)
at emitErrorNT (internal/streams/destroy.js:91:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:13616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:13616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
[Error - 9:48:13 am] Request textDocument/hover failed.
Message: Request textDocument/hover failed with message: request to https://sapui5.hana.ondemand.com/1.71.14/test-resources/sap/ca/scfld/md/designtime/api.json failed, reason: connect ETIMEDOUT 23.48.30.95:443
Code: -32603
(node:13616) UnhandledPromiseRejectionWarning: FetchError: request to https://sapui5.hana.ondemand.com/1.71.14/test-resources/sap/ca/scfld/md/designtime/api.json failed, reason: connect ETIMEDOUT 23.48.30.95:443
at ClientRequest. (c:\Users\KjaerJ.vscode\extensions\saposs.vscode-ui5-language-assistant-1.5.1\node_modules@ui5-language-assistant\language-server\dist\server.js:48289:11)
at ClientRequest.emit (events.js:203:13)
at TLSSocket.socketErrorListener (_http_client.js:399:9)
at TLSSocket.emit (events.js:203:13)
at emitErrorNT (internal/streams/destroy.js:91:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:13616) UnhandledPromiseRejectionWarning: FetchError: request to https://sapui5.hana.ondemand.com/1.71.14/test-resources/sap/ca/scfld/md/designtime/api.json failed, reason: connect ETIMEDOUT 23.48.30.95:443
at ClientRequest. (c:\Users\KjaerJ.vscode\extensions\saposs.vscode-ui5-language-assistant-1.5.1\node_modules@ui5-language-assistant\language-server\dist\server.js:48289:11)
at ClientRequest.emit (events.js:203:13)
at TLSSocket.socketErrorListener (_http_client.js:399:9)
at TLSSocket.emit (events.js:203:13)
at emitErrorNT (internal/streams/destroy.js:91:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:13616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:13616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:13616) UnhandledPromiseRejectionWarning: FetchError: request to https://sapui5.hana.ondemand.com/1.71.14/test-resources/sap/ca/scfld/md/designtime/api.json failed, reason: connect ETIMEDOUT 23.48.30.95:443
at ClientRequest. (c:\Users\KjaerJ.vscode\extensions\saposs.vscode-ui5-language-assistant-1.5.1\node_modules@ui5-language-assistant\language-server\dist\server.js:48289:11)
at ClientRequest.emit (events.js:203:13)
at TLSSocket.socketErrorListener (_http_client.js:399:9)
at TLSSocket.emit (events.js:203:13)
at emitErrorNT (internal/streams/destroy.js:91:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:13616) UnhandledPromiseRejectionWarning: FetchError: request to https://sapui5.hana.ondemand.com/1.71.14/test-resources/sap/ca/scfld/md/designtime/api.json failed, reason: connect ETIMEDOUT 23.48.30.95:443
at ClientRequest. (c:\Users\KjaerJ.vscode\extensions\saposs.vscode-ui5-language-assistant-1.5.1\node_modules@ui5-language-assistant\language-server\dist\server.js:48289:11)
at ClientRequest.emit (events.js:203:13)
at TLSSocket.socketErrorListener (_http_client.js:399:9)
at TLSSocket.emit (events.js:203:13)
at emitErrorNT (internal/streams/destroy.js:91:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:13616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:13616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
[Error - 9:48:13 am] Request textDocument/completion failed.
Message: Request textDocument/completion failed with message: request to https://sapui5.hana.ondemand.com/1.71.14/test-resources/sap/ca/scfld/md/designtime/api.json failed, reason: connect ETIMEDOUT 23.48.30.95:443
Code: -32603
(node:13616) UnhandledPromiseRejectionWarning: FetchError: request to https://sapui5.hana.ondemand.com/1.71.14/test-resources/sap/ca/scfld/md/designtime/api.json failed, reason: connect ETIMEDOUT 23.48.30.95:443
at ClientRequest. (c:\Users\KjaerJ.vscode\extensions\saposs.vscode-ui5-language-assistant-1.5.1\node_modules@ui5-language-assistant\language-server\dist\server.js:48289:11)
at ClientRequest.emit (events.js:203:13)
at TLSSocket.socketErrorListener (_http_client.js:399:9)
at TLSSocket.emit (events.js:203:13)
at emitErrorNT (internal/streams/destroy.js:91:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:13616) UnhandledPromiseRejectionWarning: FetchError: request to https://sapui5.hana.ondemand.com/1.71.14/test-resources/sap/ca/scfld/md/designtime/api.json failed, reason: connect ETIMEDOUT 23.48.30.95:443
at ClientRequest. (c:\Users\KjaerJ.vscode\extensions\saposs.vscode-ui5-language-assistant-1.5.1\node_modules@ui5-language-assistant\language-server\dist\server.js:48289:11)
at ClientRequest.emit (events.js:203:13)
at TLSSocket.socketErrorListener (_http_client.js:399:9)
at TLSSocket.emit (events.js:203:13)
at emitErrorNT (internal/streams/destroy.js:91:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:13616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:13616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)

### PR DESCRIPTION
**Pull request by ndrsg**
…work behind proxy

Added custom agent to fetcher / node-fetch to be able to GET ui5-model behind a proxy (e.g.
corporate proxy). Therefore look at environment variables HTTPS_PROXY, HTTP_PROXY and NO_PROXY and
respect them depending on request url.

I'm passing agent as any, because of incompatibility of agent-base typings:
https://github.com/TooTallNate/node-https-proxy-agent/issues/108

fix #285

### CODE REVIEW

**Comment by bd82** [comment]
## Review

### Custom User Agent vs using a different http[s] library
- Did you consider/evaluate replacing the fetch library with one that handles the proxy settings automatically?
- Could there be edge cases we are missing?
  - e.g: I checked for example that process.env["http_proxy"] === process.env["HTTP_PROXY"] (case insensitive env var names). 

### Logic structure.
Could we avoid mixing up the building of the userAgent and the `fetch` call?
e.g:

```javascript

let fetchOptions = {};

if (process.env["http_proxy"] && otherCondition) {
   fetchOptions.agent = new HttpProxyAgent(process.env["HTTP_PROXY"]);
}
else if (HTTPS_CONDITION) {
   fetchOptions.agent = new HttpsProxyAgent(process.env["HTTPS_PROXY"]);
}

// only call `fetch` once.
fetch(url, fetchOptions)
```

Basically this would enable us to extract the new logic to a **separate** function which could be useful:
- Once we fix the code coverage checks on the language-server package we will need to exclude the http-agent related logic.
- Generally cleaner code with greater separation of concerns.

### Console usage
I wonder if we should keep these or remove these.
We have an output channel in the VSCode extension, however I am not sure if it is accessible from the language server.

### ESLint errors

You can tell eslint to ignore errors in certain lines, probably something like:
- `/* eslint-disable-next-line  @typescript-eslint/no-explicit-any */`
- `// eslint-disable-next-line  @typescript-eslint/no-explicit-any`

See relevant docs:
- https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments

**Comment by tal-sapan** [comment]
Hi,

I agree with @bd82.
My comments:
1. Extract the proxy handling to a different function which will return the agent based on the URL.
1. If possible, use a library for checking the environment variables and handling edge cases (like different case of env var names, no_proxy handling - instead of substring I think it would be better to check the host).
1. Only log the usage of a proxy, and maybe also when you find the URL is in no_proxy. If the env vars are not set I don't think there is a need to log. Also, in the log it might be useful to log the proxy URL.
1. Only calculate the agent once, before iterating over `libs`. The library URL always begins with the `baseUrl` (which contains the schema and host). There is no need to calculate it for every library name, and it would prevent writing many identical logs to the console (which goes to the output channel of the extension).
1. Instead of casting to `any` you can cast to the expected type (`Agent`). If typescript doesn't accept it as-is, you can cast to `unknown` first and then to `Agent`. It is closer to your intention than `any` and explains better what you tried to do.

**Comment by ndrsg** [comment]
Hello @bd82 and @tal-sapan ,

thanks for your review, I want to reply to some points:

> Did you consider/evaluate replacing the fetch library with one that handles the proxy settings automatically?
Yes I considered, but thought better not adding an additional dependency. If you think its a better option to use, e.g. https://github.com/axios/axios , i can also try to integrate it.

> Could there be edge cases we are missing?
> e.g: I checked for example that process.env["http_proxy"] === process.env["HTTP_PROXY"] (case insensitive env var names).
Yes that's true, i forgot about JSON Case Sensitivity.

Extracting functionality to another function might be a good idea in general. fetch allows to pass a function that returns an agent instead of passing an agent directly.

> Only calculate the agent once, before iterating over libs. The library URL always begins with the baseUrl (which contains the schema and host). There is no need to calculate it for every library name, and it would prevent writing many identical logs to the console (which goes to the output channel of the extension).

Sorry, I'm not sure if I understand that correctly, can you give me an example here?

> Instead of casting to any you can cast to the expected type (Agent). If typescript doesn't accept it as-is, you can cast to unknown first and then to Agent. It is closer to your intention than any and explains better what you tried to do.

Okay.

**Comment by tal-sapan** [comment]
Hi @ndrsg,

> Yes I considered, but thought better not adding an additional dependency. If you think its a better option to use, e.g. https://github.com/axios/axios , i can also try to integrate it.
 
This library looks good to me and seems to handle more cases (for example, both lowercase and uppercase proxy env vars, no_proxy env var that contains `*`). However it seems it has a PR open regarding an issue using a proxy with https schema:
https://github.com/axios/axios/pull/3070
It seems the PR is still being worked on so maybe it will be fixed soon.

> > Only calculate the agent once, before iterating over libs. The library URL always begins with the baseUrl (which contains the schema and host). There is no need to calculate it for every library name, and it would prevent writing many identical logs to the console (which goes to the output channel of the extension).
> 
> Sorry, I'm not sure if I understand that correctly, can you give me an example here?

Sure, I'll explain in more detail.
The place where you added the calculation of the proxy is during the `fetch` call, which is executed for every UI5 library (`sap.m`, `sap.f`, `sap.tnt` etc) unless it was found in the cache. Each library definition file is downloaded from a different URL which is specific to the library, but all the URLs have the same host, so the proxy configuration will be the same for all of them. Therefore, there is no need to calculate the proxy host for every library URL. 
It's not a costly process (especially compared to the actual network call) so it doesn't matter very much, but you print the proxy to the log for every URL. Since all these logs will be the same it's redundant.
If you only perform the calculation once and reuse the same proxy configuration, the log will also be printed once.
This means moving the calculation of the proxy to right before this line:
https://github.com/SAP/ui5-language-assistant/blob/6bdccb0f44ade04dd739a9e80a25aaf492ecc730/packages/language-server/src/ui5-model.ts#L54

**Comment by bd82** [comment]
> Yes I considered, but thought better not adding an additional dependency. If you think its a better option to use, e.g. https://github.com/axios/axios , i can also try to integrate it.

Generally it is better to add a new dependency for this due to possible edge cases complexity.
However if adding a new dependency requires too much refactoring, or if there are open issues with
the 3rd party library then it's fine to implement our own solution **currently** and **defer** upgrade to a 3rd party library to the future.

Please note that `process.env` is already case insensitive but **only on windows**.
- https://nodejs.org/api/process.html#process_process_env

I guess it would **suffice** to handle all upper or all lower case on linux (HTTP_PROXY vs http_proxy)

**Comment by babuilyas** [comment]
I found a hack resolved this for me in vscode while working on other related issue.
My dev machine runs on Windows, so adopt appropriate your OS.
Windows Shell and Power Shell uses same proxy, so setup it with following command 

Step 1: C:\>netsh winhttp set proxy http://172.16.0.38:808 bypass-list="localhost;127.0.0.1" 
[Requires Admin rights]

Step 2: Launch VSCode from command with
C:\your-ui5-project> code .

Step 3: Optional confirm proxy in VScode terminal with 
C:\your-ui5-project> netsh winhttp show proxy
Result: Step 1 proxy output

Step 4: Confirm proxy is working in VScode terminal with 
C:\your-ui5-project> curl "https://www.google.com"
Result: StatusCode        : 200
           StatusDescription : OK

Now try code-completion and inline documentation etc.
It works for me 👍 and should work for you.

Credit goes to @petermuessig

**Comment by babuilyas** [comment]
Working behind a proxy in Node project is a challenge. Not all module consider the process env proxy settings when making http calls. So try my the hack shared above, and your ref. module may be using env proxy settings before http calls.

**Pull request closed without merging**
