### PR TITLE
feat: added turborepo for speed

### PR DESCRIPTION
**Pull request by uxkjaer**

### CODE REVIEW

**Comment by bd82** [comment]
why are there so many source code changes for a **tool** introduction?

**Comment by uxkjaer** [comment]
This is to come after #496, i think this PR has both of them.

**Comment by bd82** [comment]
I don't think it is a good idea to change the build tools in a project that is not very actively maintained...

**Comment by bd82** [comment]
I'll close this for now.
We can discuss it on a voice chat if you wish.

**Comment by uxkjaer** [comment]
Well the plan is that I would pick up the maintenance and make it more regular. But I'm still not a maintainer.

**Pull request closed without merging**
